services:
  - type: web
    name: cafe-south-indian
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromParam: PORT
    healthCheckPath: /

